name: Run Tests

on:
  push:
    branches: [preprod, dev]
  pull_request:
    branches: [preprod, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: portfolio

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
